image: hashicorp/terraform:light

pipelines:
  branches:
    master:
      - step:
          name: Terraform Plan
          deployment: production
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            TF_VAR_aws_access_key: $AWS_ACCESS_KEY_ID
            TF_VAR_aws_secret_key: $AWS_SECRET_ACCESS_KEY
          script:
            - terraform init
            - terraform validate
            - terraform plan -out=terraform.tfplan
          artifacts:
            - terraform.tfplan
      - step:
          name: Terraform Apply
          deployment: production
          variables:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
            TF_VAR_aws_access_key: $AWS_ACCESS_KEY_ID
            TF_VAR_aws_secret_key: $AWS_SECRET_ACCESS_KEY
          script:
            - terraform apply terraform.tfplan