image: hashicorp/terraform:light

pipelines:
  branches:
    master:
      - step:
          name: Terraform Plan
          script:
            - terraform init
            - terraform validate
            - terraform plan -out=terraform.tfplan
          artifacts:
            - terraform.tfplan
      - step:
          name: Terraform Apply
          script:
            - terraform apply terraform.tfplan