image: hashicorp/terraform

pipelines:
  custom:
    Deploy-to-prod-MFS:
      - step:
          name: Terraform plan for MFS
          script:
            - terraform init
            - terraform validate
            - terraform plan -out=terraform.tfplan
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          artifacts:
            - terraform.tfplan
      - step:
          trigger: manual
          name: Terraform apply (Manual)
          script:
            - terraform apply terraform.tfplan
          